team2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^umbrella_system/', include('umbrella_system.urls')),
    url(r'^admin/', admin.site.urls),
]

umbrella_system/urls.py
from django.conf.urls import url

from . import views

app_name = 'umbrella_system'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /umbrella_system/date/20160601/
    url(r'^date/([0-9]+)/$', views.date, name='date'),
    url(r'^room/$', views.room, name='room'),
    url(r'^table/$', views.table, name='table'),
]

umbrella_system/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class User(models.Model):
    password = models.CharField(max_length=8)
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class Order(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    time_zone_id = models.IntegerField(default=0)
    order_day = models.DateTimeField('date published')
    charge_lv = models.IntegerField(default=0)
    order_flg = models.IntegerField(default=0)

umbrella_system/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader, RequestContext
import time,datetime
import calendar
from .models import Room,Genre,User,Order



def	index(request):
	return render(request,'umbrella_system/index.html')

def	date(request, dates):
    gdate = int(dates)
    year = gdate//10000
    month = gdate//100%100
    day = gdate%100
    
    day_of_week = datetime.date(year, month, day).weekday()
    flg_holiday = False
    if (day_of_week == 5 or day_of_week == 6):
    	flg_holiday = True

    calendar.setfirstweekday(calendar.SUNDAY)
    dt = datetime.datetime(year,month,1)
    dt = datetime.datetime.fromtimestamp(time.mktime((year, month+1, 1, 0, 0, 0, 0, 0, 0)))
    next_date = dict({'year':dt.year,'month':dt.month,})
    dt = datetime.datetime.fromtimestamp(time.mktime((year, month-1, 1, 0, 0, 0, 0, 0, 0)))
    last_date = dict({'year':dt.year,'month':dt.month,})

    cal = dict({
    	'year':year,
    	'month':month,
    	'days':calendar.monthcalendar(year, month),
    })
    contexts = dict({
    	'cal':cal,
    	'next_date':next_date,
    	'last_date':last_date,
    	'flg_holiday':flg_holiday,
    	'messages': Room.objects.all(),
    })

    return HttpResponse(render(request,'umbrella_system/date.html',contexts))

def room(request):
    contexts = dict({'messages': Room.objects.all(),})

    return HttpResponse(render(request, 'umbrella_system/room.html', contexts))

def table(request):
    contexts = dict({})

    return HttpResponse(render(request, 'umbrella_system/room.html', contexts))

umbrella_system/templates/umbrella_system/_date.html
<html>
    <head>
        <title>date</title>
        <style>
            td{
                text-align:center;
            }
        </style>
    </head>
    <br>
        <h2>date</h2>
        <a href="../../{{last_date.year}}{%if last_date.month < 10%}0{%endif%}{{last_date.month}}/date"><<{{last_date.year}}年{{last_date.month}}月</a>
        <a href="../../{{next_date.year}}{%if next_date.month < 10%}0{%endif%}{{next_date.month}}/date">{{next_date.year}}年{{next_date.month}}月>></a>
        <table>
            <tr>
                <td colspan="7">{{cal.year}}年{{cal.month}}月</td>
            </tr>
            <tr>
                <td>日</td>
                <td>月</td>
                <td>火</td>
                <td>水</td>
                <td>木</td>
                <td>金</td>
                <td>土</td>
            </tr>
        {% for days in cal.days %}
            <tr>{% for day in days %}
                <td>{%if day != 0%}<a href="{{cal.year}}{%if cal.month < 10%}0{%endif%}{{cal.month}}{%if day < 10%}0{%endif%}{{day}}">{%if day < 10%}0{%endif%}{{day}}</a>{%else%}{%endif%}</td>{% endfor %}
            </tr>
            {% endfor %}
        </table>
        {{cal.dates}}
        {% url 'umbrella_system:date' 201606 %}
        {{x}}
    </body>
</html>

umbrella_system/templates/umbrella_system/_index.html
<html>
    <head>
        <title>index</title>
    </head>
    <body>
        <h2>index</h2>
    </body>
</html>

umbrella_system/templates/umbrella_system/_room.html
<html>
    <head>
        <title>index</title>
    </head>
    <body>
        <h2>index</h2>
        {{messages.all}}
        {% for room in messages.all %}
            <table border="1">
                <tr>
                    <td colspan="10">{{room}}教室</td>
                </tr>
                <tr>
                    <td>時間</td>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                    <td>8</td>
                    <td>9</td>
                </tr>
                <tr>
                    <td>予約状況</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
            </br>
        {% endfor %}
    </body>
</html>

umbrella_system/templates/umbrella_system/_table.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/table.css' %}" />

<p>
	<a href="#" id="link_hidden2" onClick="toggle_hidden2();return false;" style="display:none;">非表示</a>
	<a href="#" id="link_view2" onClick="toggle_view2();return false;">表示</a>　　　　　　　　　　　　　　
	<input type="submit" value="時間割" onclick="location.href='../zikanwari/'">
</p>
	<table border =1 id="waku" style="visibility:hidden;">



    {% for room in messages.all %}
        <td><p><a class="a" href="../yoyaku/">{{ room }}</p></td>
    {% endfor %}
<!--
	 	<td><p><a class="a" href="../yoyaku/">102</a></p></td>
	 	<td><p><a class="a" href="../yoyaku/">103</a></p></td></tr>
	 <tr><td><p><a class="a" href="../yoyaku/">201</a></p></td>
	 	<td><p><a class="a" href="../yoyaku/">202</a></p></td>
	 	<td><p><a class="a" href="../yoyaku/">203</a></p></td></tr>
	 <tr><td><p><a class="a" href="../yoyaku/">301</a></p></td>
	 	<td><p><a class="a" href="../yoyaku/">302</a></p></td>
	 	<td><p><a class="a" href="../yoyaku/">303</a></p></td></tr>
-->
	 <tr><td>倉庫</td></tr>
	 	</tr>
	</table>
	
<script language="JavaScript" type="text/javascript">
<!--
var elem2_1 = document.getElementById("waku");
var elem2_2 = document.getElementById("link_view2");
var elem2_3 = document.getElementById("link_hidden2");
function toggle_view2() {
  elem2_1.style.visibility = "visible";
  elem2_2.style.display = "none";
  elem2_3.style.display = "";
}
function toggle_hidden2() {
  elem2_1.style.visibility = "hidden";
  elem2_2.style.display = "";
  elem2_3.style.display = "none";
}
-->
</script>

umbrella_system/templates/umbrella_system/date.html
<html>
    <head>
        <title>date</title>
        <style>
            td{
                text-align:center;
            }
            .box{
            	float: left;
            }
        </style>
    </head>
    <br>
    <div class="box">
        <h2>date</h2>
        <a href="../{{last_date.year}}{%if last_date.month < 10%}0{%endif%}{{last_date.month}}01"><<{{last_date.year}}年{{last_date.month}}月</a>
        <a href="../{{next_date.year}}{%if next_date.month < 10%}0{%endif%}{{next_date.month}}01">{{next_date.year}}年{{next_date.month}}月>></a>
        <table>
            <tr>
                <td colspan="7">{{cal.year}}年{{cal.month}}月</td>
            </tr>
            <tr>
                <td>日</td>
                <td>月</td>
                <td>火</td>
                <td>水</td>
                <td>木</td>
                <td>金</td>
                <td>土</td>
            </tr>
        {% for days in cal.days %}
            <tr>{% for day in days %}
            	
               <td>{%if day != 0%}<a href="../{{cal.year}}{%if cal.month < 10%}0{%endif%}{{cal.month}}{%if day < 10%}0{%endif%}{{day}}">{%if day < 10%}0{%endif%}{{day}}</a>{%else%}{%endif%}</td>{% endfor %}
            </tr>
            {% endfor %}
        </table>
        
        {{cal.dates}}
        {% url 'umbrella_system:date' 201606 %}
        {{x}}
       </div>
       
       <div class="box">
        <h2>index</h2>
        {{messages.all}}
        {% for room in messages.all %}
	        {%if flg_holiday == True %}
	            <table id="table1" border="1">
	                <tr>
	                    <td colspan="10">{{room.name}}教室</td>
	                </tr>
	                <tr>
	                    <td>時間</td>
	                    <td>10:00~11:00</td>
	                    <td>11:15~12:15</td>
	                    <td>13:15~14:15</td>
	                    <td>14:30~15:30</td>
	                    <td>15:45~16:45</td>
	                </tr>
	                <tr>
	                    <td>予約状況</td>
	                    <td></td>
	                    <td></td>
	                    <td></td>
	                    <td></td>
	                    <td></td>
	                </tr>
	            </table>
	        {%else%}    
	            <table id="table2" border="1">
	                <tr>
	                    <td colspan="10">{{room.name}}教室</td>
	                </tr>
	                <tr>
	                    <td>時間</td>
	                    <td>15:00~16:00</td>
	                    <td>16:15~17:15</td>
	                    <td>17:30~18:30</td>
	                </tr>
	                <tr>
	                    <td>予約状況</td>
	                    <td></td>
	                    <td></td>
	                    <td></td>
	                </tr>
	            </table>
	            </br>
	         {%endif%}
        {% endfor %}
       </div>
       
    </body>
</html>

umbrella_system/templates/umbrella_system/index.html
<html>
    <head>
        <title>index</title>
    </head>
    <body>
        <h2>index</h2>
    </body>
</html>

umbrella_system/templates/umbrella_system/room.html
<html>
    <head>
        <title>index</title>
    </head>
    <body>
        <h2>index</h2>
        {{messages.all}}
        {% for room in messages.all %}
            <table border="1">
                <tr>
                    <td colspan="10">{{room}}教室</td>
                </tr>
                <tr>
                    <td>時間</td>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                    <td>8</td>
                    <td>9</td>
                </tr>
                <tr>
                    <td>予約状況</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
            </br>
        {% endfor %}
    </body>
</html>